DEMOMSQM/Controllers/PagoController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Messaging;
using System.Web;
using System.Web.Mvc;
using DEMOMSQM.Models;
using DEMOMSQM.Models.ViewModels;
namespace DEMOMSQM.Controllers
{
    public class PagoController : Controller
    {
        // GET: Pago
        public ActionResult Index()
        {
            List<ListTableViewModel> lst;
            using (DEMOPAGOEntities3 db = new DEMOPAGOEntities3())
            {
                lst = (from d in db.VENTAS
                       select new ListTableViewModel
                       {
                           Id = d.id,
                           Usuario = d.Usuario,
                           Fecha = (DateTime)d.Fecha,
                           Beneficiario = d.Beneficiario,
                           Producto = d.Producto,
                           Precio = d.Precio,
                           Email = d.Email,
                           Direccion = d.Direccion



                       }).ToList();

            }
            return View(lst);
        }
        public ActionResult RealizarPago()
        {
            return View();
        }


        public struct Payment
        {
            public string Payor, Payee;
            public int Amount;
            public string DueDate;
        }

        [HttpPost]
        public ActionResult RealizarPago(TablaViewModel model)
        {
            try {
                if (ModelState.IsValid)
                {

                    
                        var oTabla = new VENTAS();
                        Random r = new Random();

                        model.Id = r.Next(10, 900);
                        oTabla.id = model.Id;
                        oTabla.Usuario = model.Usuario;
                        oTabla.Fecha = model.Fecha;
                        oTabla.Beneficiario = model.Beneficiario;
                        oTabla.Producto = model.Producto;
                        oTabla.Precio = model.Precio;
                        oTabla.Email = model.Email;
                        oTabla.Direccion = model.Direccion;




                       
                        using (MessageQueue Testing = new MessageQueue())
                        {
                            Testing.Path = @".\private$\Testing";
                            if (!MessageQueue.Exists(Testing.Path))
                            {
                                MessageQueue.Create(Testing.Path);
                            }




                            System.Messaging.Message mymessage = new System.Messaging.Message();

                            //Payment myPayment;
                            //myPayment.Payor = "aeae";
                            //myPayment.Payee = "aea";
                            //myPayment.Amount = 12;
                            //myPayment.DueDate = "aeae";

                            mymessage.Body ="Pedido n°: "+ oTabla.id + "\n\r" +"Comprador: "+oTabla.Usuario+ "\n\r"+"Fecha: " + oTabla.Fecha + "\n\r"+"Producto: "+ oTabla.Producto + "\n\r" + "Email: " + oTabla.Email + "\n\r" + "Direccion: " + oTabla.Direccion;


                            Testing.Send(mymessage);
                        }

                    

                    return Redirect("/");
                }

            }
             catch (Exception ex)
            {
                throw new Exception(ex.Message);
            }
            return View(model);

            
           
        }
        
    }
}

DEMOMSQM/Views/Pago/Index.cshtml
@model List<DEMOMSQM.Models.ViewModels.ListTableViewModel>
@{
    ViewBag.Title = "Ventas";
}


<h2> @ViewBag.Title</h2>
<div class="row" style="text-align:right;padding:5px;">
     <a href="~/Pago/Nuevo"></a>
     </div>
<div class="row">
    <div class="col-md-12">
        <table class="table table-dark table-striped">
            <thead>
                <tr>
                    <th>ID</th>
                    <th>Usuario</th>
                    <th>Beneficiario</th>
                    <th>Fecha</th>
                    <th>Producto</th>
                    <th>Email</th>
                    <th>Direccion</th>
                    <th>Precio</th>
                </tr>
                @foreach (var oElemento in Model)
                {
            <tr>
                <td>@oElemento.Id</td>
                <td>@oElemento.Usuario</td>
                <td>@oElemento.Beneficiario</td>
                <td>@oElemento.Fecha</td>
                <td>@oElemento.Producto</td>
                <td>@oElemento.Email</td>
                <td>@oElemento.Direccion</td>
                <td>@oElemento.Precio</td>
            </tr>
                }
            </thead>
        </table>
    </div>

</div>

DEMOMSQM/Views/Pago/RealizarPago.cshtml
@model DEMOMSQM.Models.ViewModels.TablaViewModel
@{
    ViewBag.Title = "RealizarPago";
}
<style>
    body {
        background-color: #e6ebf4
    }

    .card {
        border: none;
        border-radius: 8px;
        box-shadow: 5px 6px 6px 2px #e9ecef
    }

    .heading {
        font-size: 23px;
    }

    .text {
        font-size: 16px;
        font-weight: 500;
        color: #b1b6bd
    }

    .pricing {
        border: 2px solid #304FFE;
        background-color: #f2f5ff
    }

    .business {
        font-size: 20px;
        font-weight: 500
    }

    .plan {
        color: #aba4a4
    }

    .dollar {
        font-size: 16px;
        color: #6b6b6f
    }

    .amount {
        font-size: 50px;
        font-weight: 500
    }

    .year {
        font-size: 20px;
        color: #6b6b6f;
        margin-top: 19px
    }

    .detail {
        font-size: 22px;
        font-weight: 500
    }

    .cvv {
        border: 2px solid #eee
    }

        .cvv:focus {
            box-shadow: none;
            border: 2px solid #304FFE
        }

    .email-text {
        height: 55px;
        border: 2px solid #eee
    }

        .email-text:focus {
            box-shadow: none;
            border: 2px solid #304FFE
        }

    .payment-button {
        height: 70px;
        width: 350px;
        font-size: 20px
    }
</style>
<div class="container mt-5 mb-5 d-flex justify-content-center">
    <div class="card p-5">
        <div>
            <h4 class="heading">Realiza el pago de tu compra</h4>
            <p class="text">Please make the payment to start enjoying all the features of our premium plan as soon as possible</p>
        </div>


        <div class="media">
            <div class="media-left">
                <a href="#">
                    <img class="media-object" height="200" src="https://www.geekjack.net/resources/upload/products/thumbnail2/coco_crest.jpg" alt="...">
                </a>
            </div>
            <div class="media-body">
                <h4 class="media-heading">Insignia Kiryu</h4>
                Pin badge of Kiryu Family
                Size: Approx. D 22mm Approx. thickness: 1.2mm
                Material: Copper alloy with a plastic case
                * Please note that the orders may be closed as soon as the specified production quantity is reached.
                <br />
                <h4>《Item Description》</h4>
                Price:1,500 yen(Shipping fee not included)
                Order Period: June 17 to July 1st, 18:00(JST)
                Scheduled to be shipped: Late October 2021～Late November 2021

                <div class="d-flex flex-row align-items-center"> <sup class="dollar font-weight-bold">$</sup> <span class="amount ml-1 mr-1">1,500</span> <span class="year font-weight-bold">/ c/u</span> </div> <!-- /pricing table-->
            </div>
        </div>



        <span class="detail mt-5">Detalles de Pago</span>
        @using (Html.BeginForm("RealizarPago", "Pago", FormMethod.Post))
        {
            <div class="row">
                <div class="credit rounded mt-4 d-flex justify-content-between align-items-center">
                    <div class="d-flex flex-row align-items-center">
                        <img src="https://i.imgur.com/qHX7vY1.png" class="rounded" width="70">
                        <div class="d-flex flex-column ml-3">
                            <span class="business">
                                @Html.LabelFor(d => d.Usuario)
                            </span>
                        </div>
                    </div>
                    <div>
                        @Html.TextBoxFor(d => d.Usuario, "", new { @class = "form-control", @Value = "Hugo" })
                    </div>
                </div>
                <div class="credit rounded mt-2 d-flex justify-content-between align-items-center">
                    <div class="d-flex flex-row align-items-center">
                        <div class="d-flex flex-column ml-3"> <span class="business">@Html.LabelFor(d => d.Beneficiario)</span>  </div>
                    </div>
                    <div>
                        @Html.TextBoxFor(d => d.Beneficiario, "", new { @class = "form-control", @Value = "Cover" })
                    </div>
                </div>
                <div class="credit rounded mt-2 d-flex justify-content-between align-items-center">
                    <div class="d-flex flex-row align-items-center">
                        <div class="d-flex flex-column ml-3"> <span class="business">@Html.LabelFor(d => d.Email)</span>  </div>
                    </div>
                    <div>
                        @Html.TextBoxFor(d => d.Email, "", new { @class = "form-control", @Value = "ABC@a.com" })
                    </div>
                </div>
                <div class="credit rounded mt-2 d-flex justify-content-between align-items-center">
                    <div class="d-flex flex-row align-items-center">
                        <div class="d-flex flex-column ml-3"> <span class="business">@Html.LabelFor(d => d.Direccion)</span>  </div>
                    </div>
                    <div>
                        @Html.TextBoxFor(d => d.Direccion, "", new { @class = "form-control", @Value = "Callao" })
                    </div>
                </div>


                <h6 class="mt-4 text-primary">INFORMACION ADICIONAL</h6>

                @Html.TextBoxFor(d => d.Precio, "", new { @class = "form-control", @Value = "1500" ,@readonly="readonly" })
                @Html.TextBoxFor(d => d.Producto, "", new { @class = "form-control", @Value = "KC Insignia", @readonly = "readonly" })
                @Html.TextBoxFor(d => d.Fecha, "", new { @class = "form-control", @Value = "1/1/2021 12:00:00 AM", @readonly = "readonly" })

                <div class="mt-3 justify-content-center">
                    
                    <button value="Guardar" type="submit" class="btn btn-primary btn-block payment-button">Realizar Pago <i class="fa fa-cc-paypal fa-2x" aria-hidden="true"></i></button>

                </div>

            </div>
        }



    </div>
</div>